### ISSUE TITLE
Permission errors (curse API related?)

### ISSUE THREAD

**Issue by nayab9** [layday/instawow#100]
Seeing these errors:

! curse:battlegroundenemies
  internal error: "403, message='Forbidden', url=URL('https://addons-
    ecs.forgesvc.net/api/v2/addon')"
    
This may have something to do with recent drama I've heard about but never fully understood. Are we supposed to retrieve our addons from a different location now?

**Comment by Drupi** [comment]
Curse forge closed the `api/v2/` by the end of Q1... We are doomed :d

**Comment by layday** [comment]
The error from CloudFront is:

> This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
> We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

This looks like a configuration issue on CF's end - get requests still work but not post.  No idea if they'll be fixing, but the API is supposed to be withdrawn from service tomorrow.

**Comment by nayab9** [comment]
interesting... any suggestions on what to do instead?
Do we need to hunt down each individual addon in a different location like github and switch our installation to a new URL?

**Comment by layday** [comment]
You can run `instawow reconcile --installed` to switch to an alternative host where one exists.  For GitHub add-ons, it's backed by my own [github-wow-addon-catalogue](https://github.com/layday/github-wow-addon-catalogue).  You could also try generating an access token for the new CF API from https://console.curseforge.com/ but (a) the new API is currently suffering from the same issue as the unauthenticated API with POST requests and (b) CF do not look kindly on add-on manager users generating tokens for personal use and I imagine they'll be revoking them eventually.

**Comment by nayab9** [comment]
> You can run `instawow reconcile --installed` to switch to an alternative host where one exists. For GitHub add-ons, it's backed by my own [github-wow-addon-catalogue](https://github.com/layday/github-wow-addon-catalogue). You could also try generating an access token for the new CF API from https://console.curseforge.com/ but (a) the new API is currently suffering from the same issue as the unauthenticated API with POST requests and (b) CF do not look kindly on add-on manager users generating tokens for personal use and I imagine they'll be revoking them eventually.

Thanks so much, this reconcile command is great - at least half my addons were automatically switched over to wowi or github! fantastic! less manual work to do on the remaining items. Will open a PR against the catalogue repo if I can for the remainder of addons.

**Comment by layday** [comment]
> Edit: Sorry for the spam. I ran the reconcile again and this time it worked. Not sure why.

I've had a quick look at the code and I think I know why that happened. I'll fix it later - thanks.
