### ISSUE TITLE
Got this error after updating to 1.39.1

### ISSUE THREAD

**Issue by lacerated** [layday/instawow#102]
![image](https://user-images.githubusercontent.com/32882699/169695260-328ce2e3-bd8e-45eb-b70c-7906ea22b474.png)

**Comment by layday** [comment]
Hi lacerated, the error is unrelated to the update. Details disallows distribution and the new API is as of yesterday not returning download URLs for add-ons which disallow distribution. Instawow should produce a more informative error, however.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by lacerated** [comment]
i should update it manually now?

**Comment by layday** [comment]
For the time being, that is probably your best option.  The Details author has said that they will be rehosting their add-on elsewhere soon.

**Comment by layday** [comment]
Thanks for the report :)
