### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by deadmeu** [layday/instawow#106]
I'm running Arch Linux trying to install the [instawow](https://aur.archlinux.org/packages/instawow) package via the AUR which is currently broken due to a failing test:

```
tests/test_wa_updater.py:6: in <module>
    from instawow.wa_updater import BuilderConfig, WaCompanionBuilder, WeakAura, WeakAuras
build/lib/instawow/wa_updater.py:37: in <module>
    class Auras(
/usr/lib/python3.10/site-packages/pydantic/main.py:171: in __new__
    annotations = resolve_annotations(namespace.get('__annotations__', {}), namespace.get('__module__', None))
/usr/lib/python3.10/site-packages/pydantic/typing.py:305: in resolve_annotations
    value = _eval_type(value, base_globals, None)
/usr/lib/python3.10/typing.py:327: in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
/usr/lib/python3.10/typing.py:693: in _evaluate
    type_ = _type_check(
/usr/lib/python3.10/typing.py:167: in _type_check
    raise TypeError(f"{arg} is not valid as type argument")
E   TypeError: typing.ClassVar[yarl.URL] is not valid as type argument
```
[I've found an issue raised in another project](https://github.com/samuelcolvin/pydantic/issues/3401) which seemingly had the same issue.
I'm running Python v3.10.4 and am happy to help debug and test out fixes :slightly_smiling_face:

**Comment by layday** [comment]
Indeed, this is due to a bug in Pydantic (which we no longer use).  If you'd like, you can open a PR against https://github.com/layday/instawow-dist-aur and I'll push the change to the AUR.

**Comment by layday** [comment]
I'll close this now. The AUR package has been orphaned and anybody can pick it up if they wish.
