### ISSUE TITLE
Unreconcilied issue

### ISSUE THREAD

**Issue by jcmolero** [layday/instawow#110]
I have a couple of problems
- Updating Musician never gets installed
- always the last plugin has no version info and it never updates

**Comment by layday** [comment]
Can you please provide some more info:

* Is ths in the CLI or GUI?
* Which version of instawow are you using?
* What is Musician's source?

**Comment by jcmolero** [comment]
GUI
Latest
Curseforge

Enviado desde mi iPhone

El 11/08/2022, a la(s) 4:39 p.m., layday ***@***.***> escribió:

﻿

Can you please provide some more info:

  *   Is ths in the CLI or GUI?
  *   Which version of instawow are you using?
  *   What is Musician's source?

**Comment by layday** [comment]
Do you have a CFCore access token for CurseForge? See https://github.com/layday/instawow/issues/100.

**Comment by layday** [comment]
If not, you can install Musician from either WoWI or GitHub (by pasting [its URL](https://github.com/LenweSaralonde/Musician) in the search box in instawow).

**Comment by layday** [comment]
I shall assume that my suggestions helped.
