### ISSUE TITLE
internal error: "While structuring BaseCatalogue"

### ISSUE THREAD

**Issue by lacerated** [layday/instawow#111]
For couple days i have this error when refresh addons
![image](https://user-images.githubusercontent.com/32882699/185108480-4222a3c8-deb2-4cfe-a786-9c4309de3c13.png)

Also got this error when search for addons
![image](https://user-images.githubusercontent.com/32882699/185108772-6bcdf99e-7380-4aa6-a4e1-48e23dc827bb.png)

**Comment by layday** [comment]
Thanks for the report. Could you attach your error log from `%AppData%\instawow\profiles\__jsonrpc__\logs`?

**Comment by layday** [comment]
Okay, I think Isee what's happened. Please clear your instawow cache at `%LocalAppData%\Temp\instawow` and try again.

**Comment by lacerated** [comment]
Thanks, somehow it got fixed by itself without doing anything. Probably patch related

**Comment by layday** [comment]
The catalogue is downloaded from https://github.com/layday/instawow-data/tree/data. It was fixed because I regenerated the catalogue :)
