### ISSUE TITLE
Removing Instawow cache?

### ISSUE THREAD

**Issue by hazzardr** [layday/instawow#113]
OS: Fedora 36
Other Info: wow run through battlenet / lutris main installer: https://lutris.net/games/battlenet/

Hi, I reinstalled my battlenet / world of warcraft installation, and instawow still thinks that I have all addons installed, even though it's a fresh wow / bnet install. How can I "dump the cache" of what instawow has so that I can download new addons?

Looking at the actual location (this is immediately after running `instawow configure` at this location), nothing is there. This makes sense since I just reinstalled battlenet. I think it probably has to do with it being the same path that it was when I *did* have all the addons there.

Example:
```
(py39) ➜  ~ wow list
github:funkydude/basicminimap
github:bullseiwowaddons/battlegroundenemies
github:wardz/diminish
github:brittyazel/enhancedraidframes
github:seblindfors/immersion
github:sfx-wow/masque
github:sfx-wow/masque_caith
github:mooreatv/pixelperfectalign
github:nevcairiel/shadowedunitframes
github:jobackman/spellnotifications
github:backupiseasy/threatplates
github:jordonwow/safequeue
github:layday/wow-addon-template
...

(py39) ➜  ~ ls ~/Games/battlenet/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_retail_/Interface/AddOns 
(py39) ➜  ~ 
```

Thanks!

**Comment by layday** [comment]
instawow doesn't currently offer a way to delete game profiles from the CLI. You can run `instawow configure --show-active` and nuke the `config_dir` you see in the output (or the specific profile from `{config_dir}/profiles/{profile}`).

An option to reinstall the listed add-ons would've also come in handy I suppose.

**Comment by hazzardr** [comment]
Deleting the `config_dir` solved my issue. Thanks!

**Comment by layday** [comment]
In the next version, instawow will reinstall missing add-ons when running `instawow update`.

**Comment by hazzardr** [comment]
oh sweet, thanks a lot!
