### ISSUE TITLE
How do I install in on win7?

### ISSUE THREAD

**Issue by hasnogaems** [layday/instawow#117]
I installed gui msi, now what should I do with cli zip ? Just running instawow-gui.exe gives error https://imgur.com/a/rN6rUHi

**Comment by layday** [comment]
I'm sorry, I'm not sure what might be causing that and I'm not aware of the Windows binaries being incompatible with Windows 7.

**Comment by layday** [comment]
I'll close this now, sorry that I wasn't able to help.
