### ISSUE TITLE
Elevated CPU usage on Linux

### ISSUE THREAD

**Issue by supra89t** [layday/instawow#118]
Hello,

I'm using the app-image (1.45.0) for Linux (Arch 5.19) and the application is working well. However there seems to be a little issue when I open the app.

![Screenshot_20220916_143614](https://user-images.githubusercontent.com/25457950/190708509-e44534c5-f512-425b-85f3-cd532d7fecff.png)

I have added my github access token. The application still works, and it updates and installs/removes add-ons. There is just that popup each time I open the app or refresh the list.

Thank you,
Jonathan

**Comment by layday** [comment]
Thanks for the report. Is this a recurring issue or has it only been happening today?  Does it happen with other sources or just `wowi`?

**Comment by supra89t** [comment]
To be honest, I installed this application 2 days ago. Its been that way since then. I know the last release was 8 or 9 days ago now so before that I do not know.

Its happening for Tukui too:
![image](https://user-images.githubusercontent.com/25457950/190717633-ae2b8ac9-0f1c-41b3-a3eb-39122610eabb.png)

**Comment by supra89t** [comment]
Its also CPU hungry for doing nothing... 
![image](https://user-images.githubusercontent.com/25457950/190725892-406c5b1a-c7c0-45e0-ad29-500183516506.png)

This is it being idle for hours now.

**Comment by layday** [comment]
These are three separate issues.

The first one is most likely [this](https://github.com/aio-libs/aiohttp/issues/3904) bug in one of the libraries that we use.

The second one was a bug in instawow. I've pushed a fix.

The third one I'll need to investigate when I have more time.

**Comment by supra89t** [comment]
Confirmed, no more errors on opening the application or refreshing.

Performance is already better too! 1.5-1.8% CPU usage on a 5700X ***Spoke too soon, its at 8% after being idle for a few mins

**Comment by layday** [comment]
Would you be willing to try the development build from https://github.com/layday/instawow/actions/runs/3072773140 to see if CPU usage has gone down at all?

**Comment by supra89t** [comment]
Will do, I'll install it when I get home.

**Comment by supra89t** [comment]
Its doing the same thing.

Open application CPU usage = 1-2%
Wait 1 Min
Application CPU usage = 7-8%

**Comment by layday** [comment]
Closing for the same reason as #138.
