### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by dieterdanger** [layday/instawow#12]
Sorry to bug you once again, but with version 1.2.1 I receive  encountered PermissionError  when I try to install or update addons.

**Comment by layday** [comment]
Please paste the full trace from error.log in your instawow profile.

**Comment by dieterdanger** [comment]
Where is error.log located? I'm using the pip-version.

**Comment by dieterdanger** [comment]
Sorry, found it myself 
`2019-06-29 09:23:15.898 | ERROR    | instawow.manager:intercept:316 - internal error
Traceback (most recent call last):

  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\Scripts\instawow-script.py", line 11, in <module>
    load_entry_point('instawow==1.2.1', 'console_scripts', 'instawow')()
    -> <function load_entry_point at 0x03C67A98>

  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> ()
           |    -> <bound method BaseCommand.main of <instawow.cli._OrigCmdOrderGroup object at 0x04D315B0>>
           -> <instawow.cli._OrigCmdOrderGroup object at 0x04D315B0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
         |    |      -> <click.core.Context object at 0x01971630>
         |    -> <bound method MultiCommand.invoke of <instawow.cli._OrigCmdOrderGroup object at 0x04D315B0>>
         -> <instawow.cli._OrigCmdOrderGroup object at 0x04D315B0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           |               |       |       |      -> <click.core.Context object at 0x03F167D0>
           |               |       |       -> <bound method Command.invoke of <click.core.Command object at 0x04D31810>>
           |               |       -> <click.core.Command object at 0x04D31810>
           |               -> <click.core.Context object at 0x03F167D0>
           -> <function MultiCommand.invoke.<locals>._process_result at 0x01910810>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           |   |      |    |           |   -> {'addons': [('curse:addonskins', _Parts(origin='curse', id_or_slug='addonskins'))], 'strategy': 'default', 'replace': False}
           |   |      |    |           -> <click.core.Context object at 0x03F167D0>
           |   |      |    -> <function install at 0x04D4C5D0>
           |   |      -> <click.core.Command object at 0x04D31810>
           |   -> <bound method Context.invoke of <click.core.Context object at 0x03F167D0>>
           -> <click.core.Context object at 0x03F167D0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
           |         |       -> {'addons': [('curse:addonskins', _Parts(origin='curse', id_or_slug='addonskins'))], 'strategy': 'default', 'replace': False}
           |         -> ()
           -> <function install at 0x04D4C5D0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           | |                           |       -> {'addons': [('curse:addonskins', _Parts(origin='curse', id_or_slug='addonskins'))], 'strategy': 'default', 'replace': False}
           | |                           -> ()
           | -> <function get_current_context at 0x03F8DA08>
           -> <function install at 0x04D4C588>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\cli.py", line 214, in install
    manager.install_many((*p, strategy, replace) for _, p in addons))
    |       |                 |         |                    -> [('curse:addonskins', _Parts(origin='curse', id_or_slug='addonskins'))]
    |       |                 |         -> False
    |       |                 -> 'default'
    |       -> <bound method CliManager.install_many of <instawow.manager.CliManager object at 0x03F9FFB0>>
    -> <instawow.manager.CliManager object at 0x03F9FFB0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 379, in install_many
    return self.run(install_many())
           |    |   -> <function CliManager.install_many.<locals>.install_many at 0x04DCCDF8>
           |    -> <bound method Manager.run of <instawow.manager.CliManager object at 0x03F9FFB0>>
           -> <instawow.manager.CliManager object at 0x03F9FFB0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 173, in run
    return cv.copy_context().run(runner)
           |  |                  -> <function Manager.run.<locals>.runner at 0x0528CD20>
           |  -> <built-in function copy_context>
           -> <module 'contextvars' from 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\contextvars.py'>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 171, in runner
    return _loop.get().run_until_complete(arunner())
           |     |                        -> <function Manager.run.<locals>.runner.<locals>.arunner at 0x0528CE40>
           |     -> <built-in method get of ContextVar object at 0x04B093B0>
           -> <ContextVar name='_loop' at 0x04B093B0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
    |    -> <bound method BaseEventLoop.run_forever of <_WindowsSelectorEventLoop running=True closed=False debug=False>>
    -> <_WindowsSelectorEventLoop running=True closed=False debug=False>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
    |    -> <bound method BaseEventLoop._run_once of <_WindowsSelectorEventLoop running=True closed=False debug=False>>
    -> <_WindowsSelectorEventLoop running=True closed=False debug=False>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
    |      -> <bound method Handle._run of <Handle <TaskWakeupMethWrapper object at 0x05963930>(<Future finis...wendet wird')>)>>
    -> <Handle <TaskWakeupMethWrapper object at 0x05963930>(<Future finis...wendet wird')>)>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    |    |        |   |    |           |    -> (<Future finished exception=PermissionError(13, 'Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozes...
    |    |        |   |    |           -> <Handle <TaskWakeupMethWrapper object at 0x05963930>(<Future finis...wendet wird')>)>
    |    |        |   |    -> <TaskWakeupMethWrapper object at 0x05963930>
    |    |        |   -> <Handle <TaskWakeupMethWrapper object at 0x05963930>(<Future finis...wendet wird')>)>
    |    |        -> <built-in method run of Context object at 0x0528AFD0>
    |    -> <Context object at 0x0528AFD0>
    -> <Handle <TaskWakeupMethWrapper object at 0x05963930>(<Future finis...wendet wird')>)>
> File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 312, in intercept
    self.set_result(await awaitable)
    |    |                -> <coroutine object Manager.to_install.<locals>.install at 0x052C9390>
    |    -> <built-in method set_result of SafeFuture object at 0x0528CED0>
    -> <SafeFuture pending>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 201, in install
    await archive.extract(self.config.addon_dir)
          |       |       |    |      -> WindowsPath('C:/Users/username/Dropbox/games/wow/sync/Interface/AddOns')
          |       |       |    -> <instawow.config.Config object at 0x04D31530>
          |       |       -> <instawow.manager.CliManager object at 0x03F9FFB0>
          |       -> <bound method _Archive.extract of <instawow.manager._Archive object at 0x058B9BD0>>
          -> <instawow.manager._Archive object at 0x058B9BD0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 85, in extract
    return await run_in_thread(extract_)()
                 |             -> <function _Archive.extract.<locals>.extract_ at 0x05643DF8>
                 -> <function run_in_thread at 0x03FD63D8>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             |        |            -> None
             |        -> None
             -> None
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instawow\manager.py", line 82, in extract_
    self._callback()
    |    -> <bound method Path.unlink of WindowsPath('C:/Users/username/AppData/Local/Temp/instawow-vbpbtja_.zip')>
    -> <instawow.manager._Archive object at 0x058B9BD0>
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1277, in unlink
    self._accessor.unlink(self)
    |    |         |      -> WindowsPath('C:/Users/username/AppData/Local/Temp/instawow-vbpbtja_.zip')
    |    |         -> <built-in function unlink>
    |    -> <pathlib._NormalAccessor object at 0x03FBED30>
    -> WindowsPath('C:/Users/username/AppData/Local/Temp/instawow-vbpbtja_.zip')

PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\username\\AppData\\Local\\Temp\\instawow-vbpbtja_.zip'
`
