### ISSUE TITLE
Instawow Search Showing Wrong Version of Addon

### ISSUE THREAD

**Issue by vleach** [layday/instawow#120]
Hi,
I'm having an issue with the Instawow search pulling the 30400.2-release version of Nameplateauras, when I'm trying to install the 90207.2-release.
Screenshots:
![image](https://user-images.githubusercontent.com/39882841/192153823-fbf9ce5b-7786-4c56-8c5d-4f3cde1fe57a.png)
![image](https://user-images.githubusercontent.com/39882841/192153851-1dc2563f-d5bf-4c7d-bc7a-c1ae4abc6668.png)

**Comment by layday** [comment]
The `30400.2-release` version's release metadata in `release.json` are malformed. It contains the following:

```json
{
  "releases": [
    {
      "filename": "NameplateAuras-30400.2-release.zip",
      "nolib": false,
      "metadata": [{ "flavor": "mainline", "interface": 30400 }]
    }
  ]
}
```

The flavor cannot be `mainline` if the interface version is `30400`.  Please report this issue to the add-on's author.
