### ISSUE TITLE
Impossible to finish the reconciliation step on GUI on Windows 10

### ISSUE THREAD

**Issue by Minganie** [layday/instawow#123]
If you have addons that the plugin can't find (ex. https://www.curseforge.com/wow/addons/pettracker) already installed, the reconciliation process never finishes. It keeps saying "install" or "automate" but there are no reconciliation options for your addons (ex. PetTracker, PetTracker_Config, PetTracker_Battle, etc.). You *can* go to the Installed tab, which is where I assume I will get info when a plugin updates, but some warning or something that the remaining addons cannot be solved would be clearer for the end user. (Also, what's wrong with PetTracker? Is it because it's a multi-folder addon that it's not working?)

**Comment by layday** [comment]
Yeah, at the very least the 'install' and 'automate' buttons should be disabled.

> Also, what's wrong with PetTracker? Is it because it's a multi-folder addon that it's not working?

PetTracker is only available from the OW client, unfortunately - the author does not allow [third-party distribution](https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle).

**Comment by layday** [comment]
Message that a match wasn't found has been added in v2.1.0.
