### ISSUE TITLE
Internal JSON-RPC Error in new ARM macs

### ISSUE THREAD

**Issue by Gustavo-Rodriguez** [layday/instawow#126]
This issue is limited to the instawow gui. 

When searching for addons in the instawow-gui I am presented with an Internal JSON-RPC Error. The error references the processor architecture and that there is an incompatible processor for /Applications/instawow-gui.app/Contents/Resources/app_packages/rapidfuzz/distance/metrics_cpp.cpython_210-darwin.so

This error Only occurs when Searching, I am able to delete existing addons (added via the CLI). Manually deleting an addon folder does not trigger an install the way that the delete button seems to do.

The CLI allows me to search, update, remove, and install addons, this is limited to the GUI.

<img width="795" alt="Screenshot 2022-12-08 at 4 32 59 PM" src="https://user-images.githubusercontent.com/55159586/206573153-ce76d716-8240-4b68-a6c6-6c9abb60a5f9.png">

**Comment by layday** [comment]
Thanks for the detailed report.  This is an issue with how the app's built - despite supporting both Intel and ARM natively, Python extensions are installed for the x64 architecture only.  What you could do is force macOS to run instawow in Rosetta from the info pane.

**Comment by layday** [comment]
Fixed in v2.1.0.
