### ISSUE TITLE
ms-win-core-path missing from 2.1.1

### ISSUE THREAD

**Issue by vmid** [layday/instawow#129]
After downloading and unzipping  instawow-cli-2.1.1-windows-latest.zip instawow-standalone.exe shows the following error (see pic).
The dll mentioned in the error message does indeed seem to be missing from the root directory.

![instawow-standalone_win_211](https://user-images.githubusercontent.com/125336417/218641790-ba41ca83-9354-4d60-be70-9a6a319989b8.jpg)

**Comment by layday** [comment]
Presumably this is https://github.com/python/cpython/issues/85584. Windows 7 is not supported. Sorry :(
