### ISSUE TITLE
instawow update encountered OSError

### ISSUE THREAD

**Issue by Booleanperspective** [layday/instawow#13]
`! curse:bartender4                                                                                                
  encountered OSError                                                                                             
! curse:emote-splitter                                                                                            
  encountered OSError                                                                                             
! curse:bagnon                                                                                                    
  encountered OSError
! curse:total-rp-3-extended
  encountered OSError
! curse:total-rp-3
  encountered OSError
! curse:tomtom
  encountered OSError
! curse:weakauras-2
  encountered OSError
! curse:listener
  encountered OSError
! curse:gladius
  encountered OSError
! curse:cross-rp
  encountered OSError
! curse:rp-friends
  encountered OSError`
Arch Linux on Python 3.7.3 on `instawow update` encountered OSError. Any known solution?

**Comment by layday** [comment]
Please paste the full trace from error.log in your instawow profile.

**Comment by Booleanperspective** [comment]
`2019-06-28 23:42:04.162 | ERROR    | instawow.manager:intercept:317 - internal error
Traceback (most recent call last):

  File "/home/netrunner/.local/bin/instawow", line 11, in <module>
    load_entry_point('instawow==1.2.1', 'console_scripts', 'instawow')()
    └ <function load_entry_point at 0x7f76d0dc9620>

  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <bound method BaseCommand.main of <instawow.cli._OrigCmdOrderGroup object at 0x7f76d1a36dd8>>
           └ <instawow.cli._OrigCmdOrderGroup object at 0x7f76d1a36dd8>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f76d0d34208>
         │    └ <bound method MultiCommand.invoke of <instawow.cli._OrigCmdOrderGroup object at 0x7f76d1a36dd8>>
         └ <instawow.cli._OrigCmdOrderGroup object at 0x7f76d1a36dd8>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f76d08870f0>
           │               │       │       └ <bound method Command.invoke of <click.core.Command object at 0x7f76cd326e48>>
           │               │       └ <click.core.Command object at 0x7f76cd326e48>
           │               └ <click.core.Context object at 0x7f76d08870f0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f76d1bf81e0>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'addons': [], 'strategy': None}
           │   │      │    │           └ <click.core.Context object at 0x7f76d08870f0>
           │   │      │    └ <function update at 0x7f76cd2d0d08>
           │   │      └ <click.core.Command object at 0x7f76cd326e48>
           │   └ <bound method Context.invoke of <click.core.Context object at 0x7f76d08870f0>>
           └ <click.core.Context object at 0x7f76d08870f0>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'addons': [], 'strategy': None}
           │         └ ()
           └ <function update at 0x7f76cd2d0d08>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           │ │                           │       └ {'addons': [], 'strategy': None}
           │ │                           └ ()
           │ └ <function get_current_context at 0x7f76d16b7400>
           └ <function update at 0x7f76cd2d0b70>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/cli.py", line 240, in update
    manager.update_many(p for _, p in addons))
    │       │                         └ [('curse:bartender4', ('curse', 'bartender4')), ('curse:emote-splitter', ('curse', 'emote-splitter')), ('curse:bagnon', ('curse'...
    │       └ <bound method CliManager.update_many of <instawow.manager.CliManager object at 0x7f76d09f0ef0>>
    └ <instawow.manager.CliManager object at 0x7f76d09f0ef0>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 390, in update_many
    return self.run(update_many())
           │    │   └ <function CliManager.update_many.<locals>.update_many at 0x7f76cceaa730>
           │    └ <bound method Manager.run of <instawow.manager.CliManager object at 0x7f76d09f0ef0>>
           └ <instawow.manager.CliManager object at 0x7f76d09f0ef0>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 173, in run
    return cv.copy_context().run(runner)
           │  │                  └ <function Manager.run.<locals>.runner at 0x7f76cc5e2ea0>
           │  └ <built-in function copy_context>
           └ <module 'contextvars' from '/usr/lib/python3.7/contextvars.py'>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 171, in runner
    return _loop.get().run_until_complete(arunner())
           │     │                        └ <function Manager.run.<locals>.runner.<locals>.arunner at 0x7f76cc5e2f28>
           │     └ <built-in method get of ContextVar object at 0x7f76cd329200>
           └ <ContextVar name='_loop' at 0x7f76cd329200>
> File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 313, in intercept
    self.set_result(await awaitable)
    │    │                └ <coroutine object Manager.to_update.<locals>.update at 0x7f76afd1c548>
    │    └ <built-in method set_result of SafeFuture object at 0x7f76afd1cf48>
    └ <SafeFuture pending>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 229, in update
    for f in pkg.folders), dir_name)
             │   │         └ PurePosixPath('/tmp/instawow-ip560oim')
             │   └ [<instawow.models.PkgFolder object at 0x7f76afd930b8>]
             └ <instawow.models.Pkg object at 0x7f76c63bf8d0>
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 65, in move
    await run_in_thread(move_)()
          │             └ <function move.<locals>.move_ at 0x7f76afd7de18>
          └ <function run_in_thread at 0x7f76d0bd3048>
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None
  File "/home/netrunner/.local/pipx/venvs/instawow/lib/python3.7/site-packages/instawow/manager.py", line 63, in move_
    path.rename(dest / path.name)
    │    │      │      │    └ 'RP_Friends'
    │    │      │      └ PosixPath('/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns/RP_Fr...
    │    │      └ PurePosixPath('/tmp/instawow-ip560oim')
    │    └ <bound method Path.rename of PosixPath('/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_r...
    └ PosixPath('/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns/RP_Fr...
  File "/usr/lib/python3.7/pathlib.py", line 1312, in rename
    self._accessor.rename(self, target)
    │    │         │      │     └ PurePosixPath('/tmp/instawow-ip560oim/RP_Friends')
    │    │         │      └ PosixPath('/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns/RP_Fr...
    │    │         └ <built-in function rename>
    │    └ <pathlib._NormalAccessor object at 0x7f76d0be7860>
    └ PosixPath('/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns/RP_Fr...

OSError: [Errno 18] Invalid cross-device link: '/home/netrunner/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns/RP_Friends' -> '/tmp/instawow-ip560oim/RP_Friends'`
Looks like it's doing this for all of the addons.

**Comment by layday** [comment]
Should be fixed in 1.2.2.  Thanks for the report.
