### ISSUE TITLE
AIOHTTP: Event loop closed

### ISSUE THREAD

**Issue by LordFckHelmchen** [layday/instawow#133]
Hey @layday I recently updated to 3.0 and it appears the error mentioned in issues #31 is there again:

My Setup:
| Name | Version |
| -| - |
| Windows | Version 10.0.19045.3155 | 
| Python|3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32|
|Installed packages (pip freeze)|<pre>aiohttp==3.8.4<br>aiohttp-client-cache==0.8.1<br>aiohttp-rpc==0.7.1<br>aiosignal==1.2.0<br>aiosqlite==0.17.0<br>alembic==1.11.1<br>appdirs==1.4.4<br>async-timeout==4.0.2<br>attrs==23.1.0<br>cattrs==23.1.2<br>cffi==1.15.1<br>chardet==4.0.0<br>charset-normalizer==2.1.1<br>click==8.1.4<br>clr-loader==0.2.4<br>colorama==0.4.4<br>colosseum==0.2.0<br>exceptiongroup==1.0.4<br>frozenlist==1.3.1<br>greenlet==1.1.0<br>idna==3.1<br>instawow==3.0.0<br>iso8601==1.0.2<br>itsdangerous==2.1.2<br>jarowinkler==1.2.1<br>jedi==0.18.2<br>jellyfish==0.8.2<br>Jinja2==3.0.3<br>loguru==0.7.0<br>Mako==1.2.4<br>MarkupSafe==2.0.1<br>multidict==5.1.0<br>packaging==23.1<br>parso==0.8.3<br>pluggy==0.13.1<br>prompt-toolkit==3.0.31<br>ptpython==3.0.21<br>pycparser==2.21<br>pydantic==1.9.0<br>Pygments==2.13.0<br>python-dateutil==2.8.1<br>python-editor==1.0.4<br>python-forge==18.6.0<br>pythonnet==3.0.0.post1<br>questionary==1.10.0<br>rapidfuzz==2.13.6<br>six==1.16.0<br>SQLAlchemy==2.0.18<br>toga-core==0.2.15<br>typing_extensions==4.3.0<br>url-normalize==1.4.3<br>wcwidth==0.2.5<br>win32-setctime==1.0.3<br>yarl==1.8.1<br></pre>|
| Git Bash | Git for Windows 2.41.0.windows.1 (64-bit)|

I updated aiohttp to the most recent version (for py3.9), but calling `instawow update` still causes the error (from cmd & Git Bash):
```bash
❯ instawow --debug update
2023-07-15 11:26:35.030 | INFO     | instawow.wa_updater:extract_installed_auras:171
  loading C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<MY_ACC>\SavedVariables\WeakAuras.lua from cache at C:\Users\<MY_USER>\AppData\Local\Temp\instawow\cache\103d1d1b8368cf55e16a8d6204a1b921
2023-07-15 11:26:35.038 | INFO     | instawow.wa_updater:extract_installed_auras:171
  loading C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<MY_ACC>\SavedVariables\Plater.lua from cache at C:\Users\<MY_USER>\AppData\Local\Temp\instawow\cache\a1027651d1452fba2a15095ab867c210
✗ tukui:13-benikui-wotlk
  package does not exist
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000185D88434C0>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Any thoughts?

**Comment by layday** [comment]
Thanks for the detailed report!  I think I might've been a little too eager to remove the workaround; I could swear the issue was fixed in Python 3.9, but it looks like it was only backported as far as 3.10 (https://github.com/python/cpython/issues/92841).

**Comment by layday** [comment]
Interestingly this error does not appear in CI: https://github.com/layday/instawow/actions/runs/5562045095/jobs/10160107275.

**Comment by layday** [comment]
Should be fixed in v3.0.1.

**Comment by LordFckHelmchen** [comment]
Hey @layday thanks for the quick action! Regarding the missing CLI - could that be because Pytest [swallows your cli output](https://stackoverflow.com/questions/14405063/how-can-i-see-normal-print-output-created-during-pytest-run) and only shows it if your test fails?

**Comment by layday** [comment]
On closer inspection I think it's cuz we're reusing the event loop for CLI tests (we are not spawning a new Python process) and this error is only emitted when the loop is shutting down.
