### ISSUE TITLE
Request to adopt AUR package

### ISSUE THREAD

**Issue by 99linesofcode** [layday/instawow#135]
As an Arch user I enjoy being able to install and manage packages such as these through the AUR repository. Someone has kindly provided a package for `instawow` in the past but has since abandoned it. Would you be willing to adopt it and keep it in sync?

I believe you could create a `instawow-git` package that automatically updates when master gets updated as long as the build process hasn't changed. In that case I would probably adopt the former and sunset it and introduce an official `*-git` variant to minimize overhead.

**Comment by 99linesofcode** [comment]
You can find and adopt the current package here: https://aur.archlinux.org/packages/instawow

**Comment by layday** [comment]
Hi, I did assume ownership of the AUR package for a while (see https://github.com/layday/instawow-dist-aur), but as a non-Arch user, it was difficult for me to maintain.  I'd be happy for you or anybody else to adopt the AUR package; if I can assist in any way with automating the generation of Arch packages from git, please let me know.

**Comment by 99linesofcode** [comment]
Hey,

Totally understandable. It would be rather cumbersome to test that it works correctly.

I'm not familiar with building AUR packages and am currently not looking to take on any additional load myself. I'll close this for now and might come back on that at a later point in time.

Leaving this here as a reference for when I or someone else that would like to volunteer:

https://wiki.archlinux.org/title/Python_package_guidelines
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=solaar-git
