### ISSUE TITLE
Feature request: basic download and extract

### ISSUE THREAD

**Issue by 99linesofcode** [layday/instawow#136]
Many addons either do not publish releases or have not adhered to that convention in the past, haven't been updated in years, but are still usable in older game clients.

Would it be possible to introduce another installation method that simply downloads and extracts a Github repository? This could be very simply based on git cloning and pulling similarly to what https://gitlab.com/woblight/GitAddonsManager does.

**Comment by layday** [comment]
I've thought of this in the past, but most add-on repos are not structured in a way that a snapshot of the repo is installable, e.g. the add-on might not be located at the root or might need to be built, even if that's just to e.g. interpolate the version number in the TOC file or grab the translations from CurseForge. There's a real risk of users installing broken add-ons 'cause they picked the wrong source or installation method and possibly going on to complain to add-on authors - I can't imagine they'd appreciate that.  Maybe there's still some way we can accommodate this use case, but I think I'd need to see some examples.

As an aside, *instawow* is [extensible](https://github.com/layday/instawow?tab=readme-ov-file#plug-ins), so you could potentially write a plug-in that does this.

**Comment by 99linesofcode** [comment]
When you say most add-ons are you referring to add-ons for retail or in general?

Cause most of the add-ons I've installed recently are just plain old git repositories that you pull into the `addons` folder and you are good to go. Personally I feel that you should be able to assume that your users read the manual and figure out which installation method to use but I understand your point and wouldn't want to burden you with any additional support overhead.

In order to solve my own use case I settled on creating a private repository with my personal configuration files and git submodules for all the addons I need. That actually works nicely cause it will allow me to keep everything together and stored on Github in the inevitable event I forget to migrate it over.

**Comment by layday** [comment]
I'm referring to currently maintained add-ons for the official version of the game.  https://github.com/BigWigsMods/packager has been adopted almost universally,[^1] and add-ons which use packager need to be packaged before installation.

[^1]: You can assume that the vast majority of addons for which `has_release_json` is true on [this table](https://github.com/layday/github-wow-addon-catalogue/blob/main/addons.csv) are using packager, and many of those that don't were published before packager added support for `release.json`.
