### ISSUE TITLE
AppImage hangs on close

### ISSUE THREAD

**Issue by zJoul** [layday/instawow#138]
Hello,

The appimage won't launch, with a cryptic error : 
```
proot error: '/tmp/.mount_instawc5sHYC/usr/bin/python3' not found (root = /, cwd = /tmp, $PATH=(null))
fatal error: see `proot --help`.
```

Version used : 3.1.0 (on the [release page](https://github.com/layday/instawow/releases/tag/v3.1.0))

Tried on two different machine, same result. At first, I thought it was a problem with the deps for the AppImage, but I tried with the ajour AppImage and it was working fine.

I guess it's linked to the `linuxdeploy-plugin-zzzinstawowwebkit2gtk.sh` script since this is the only reference to proot but I'm not familiar with appimage bundling (?)

**Comment by layday** [comment]
Hi, thanks for the report. Could you try the version from https://github.com/layday/instawow/actions/runs/6853292779?

**Comment by zJoul** [comment]
It launch :tada: 
But when I try to close it, it hangs… and I need to kill it manually (both the appimage process, and the /tmp/.mountXXXX/ stuff) but it's maybe unrelated

(I don't have any WoW folder on this computer, so no config was done, only launch and close)

**Comment by torkus** [comment]
it's a stretch, but @zJoul are you executing this from within `/tmp` in each case? perhaps try `/tmp/foo` ?

@layday , do you remember when I once tried instawow and it bugged out immediately because I was running it from `/tmp` ?

**Comment by layday** [comment]
Thanks for cross-checking. Could either of you give https://github.com/layday/instawow/actions/runs/6919535217 a try?

**Comment by torkus** [comment]
Launches, but `instawow-gui -> Quit instawow-gui` still hangs.

**Comment by torkus** [comment]
breakdown of downloads: 
https://somsubhra.github.io/github-release-stats/?username=layday&repository=instawow&page=1&per_page=10

seems like the majority of your downloads comes from the windows world, those `.msi` and `pc-windows-msvc.zip` but it's a pretty even spread across formats.

Any idea on download numbers for nix?

**Comment by layday** [comment]
Unsure but I doubt it’s more than a handful. The majority of downloads come from PyPI: https://www.pepy.tech/projects/Instawow

**Comment by layday** [comment]
Addressed in https://github.com/layday/instawow/commit/77e95d71a6101195a8804d7c4e1e3b84d5f62223.
