### ISSUE TITLE
Can users add custom addon sources?

### ISSUE THREAD

**Issue by Char11e** [layday/instawow#141]
Currently I want to update the addon from my own github or gitlab, not sure if it can be supported?

Thanks~

**Comment by layday** [comment]
GitHub releases are supported out of the box.  You can add custom sources using [plug-ins](https://github.com/layday/instawow/tree/main/tests/plugin).

**Comment by Char11e** [comment]
Thank you for sharing your information.

In addition, when I installed instawow-gui-3.2.0.msi on Win10, I encountered windows defednder which considered instawow-gui-3.2.0.msi to be unsafe software.

https://shop.certum.eu/open-source-code-signing-on-simplysign.html
Will sponsorship for Open Source Code Signing in the Cloud be required?

**Comment by layday** [comment]
Yes, but it would require modifying the installation.  Are you not able to use the provided GitHub source?

**Comment by Char11e** [comment]
Do you mean that I need to modify the code in the project that belongs to the github addon source settings and then package it into a gui.exe file?

Since this is my first time contacting your project and I don’t understand the entire structure yet, could you discuss with me which files need to be modified?

**Comment by layday** [comment]
Could you link to the addon you’d like to install?

Sent with [Proton Mail](https://proton.me/) secure email.
