### ISSUE TITLE
No Files Found for Githb Hosted Addon

### ISSUE THREAD

**Issue by austinrr** [layday/instawow#143]
I'm not sure why, but when I try and install an addon from a repo I setup I get the error `no files found for: any_flavour=None; any_release_type=None;`. As far as I can tell, the release.json is formatted correctly and the addon zip filename in the release assets matches file file name in the release.json. 

Any help would be appreciated, link to repo is below.

https://github.com/austinrr/leatrixplus-mirror

**Comment by layday** [comment]
The add-on is only available for Classic. Are you trying to install it in Classic?

**Comment by austinrr** [comment]
> The add-on is only available for Classic. Are you trying to install it in Classic?

Yes.

**Comment by layday** [comment]
It works for me. Compare your config with mine:

```json
$ instawow configure --show-active
{
  "global_config": {
    "config_dir": "/[...]/code/instawow/foo",
    "temp_dir": "/tmp/instawowt",
    "state_dir": "/[...]/.local/state/instawow",
    "auto_update_check": true,
    "access_tokens": {
      "cfcore": null,
      "github": null,
      "wago": null,
      "wago_addons": null
    },
    "profiles": [
      "__default__"
    ]
  },
  "profile": "__default__",
  "addon_dir": "/[...]/code/instawow/bar",
  "game_flavour": "vanilla_classic"
}
```

**Comment by layday** [comment]
To clarify, this add-on is only compatible with Classic Era servers and not WotLK Classic.

**Comment by austinrr** [comment]
Thank you very much. Figures it would be some thing as simple as

` "game_flavour": "vanilla_classic"` vs what I had ` "game_flavour": "classic"`
