### ISSUE TITLE
appimage not uptodate

### ISSUE THREAD

**Issue by peterweissbier** [layday/instawow#144]
its just 4.3.0 version and there is no 4.4.0 version. sadly it doesnt start for me on archlinux.

Gtk-Message: 23:34:51.551: Failed to load module "canberra-gtk-module"

**Comment by layday** [comment]
Hi, app images are no longer supported and have been replaced by flatpaks.

**Comment by peterweissbier** [comment]
sadly the flatpak is borked and it only shows the Documents folder in home

**Comment by layday** [comment]
Well, that does sound less than ideal.  Looks like I forgot to give the flatpak full disk access. Thanks!
