### ISSUE TITLE
cant find addons on windows

### ISSUE THREAD

**Issue by peterweissbier** [layday/instawow#145]
it cannot find addons on windows. another problem is that sometimes the program just stays blank.
let me know if you need more information, here is a biiiig log upload

[error.log](https://github.com/user-attachments/files/15916415/error.log)

**Comment by layday** [comment]
You seem to have exceeded your GitHub rate limit.  If you are using the CLI, run `instawow configure global_config.access_tokens.github`. If you are using the GUI, open the global config pane (cog on the top left), and press "generate" next to GitHub.

**Comment by peterweissbier** [comment]
i did that and the addons still wont show up

**Comment by layday** [comment]
Do you mean that you don’t get any search results?

**Comment by layday** [comment]
If this happens during reconciliation, that no matches appear, I suggest upgrading to v4.4.1 if you haven't already and try again.

**Comment by peterweissbier** [comment]
addons now started to show up on v4.4.1, thanks!
