### ISSUE TITLE
blank program

### ISSUE THREAD

**Issue by peterweissbier** [layday/instawow#146]
its like a 50/50 chance, sometimes the program shows like this, i need to reopen it to fix it
![2024-06-22_15-42_1](https://github.com/layday/instawow/assets/140187896/7a989e73-854d-4c90-8113-2d731ce48657)

**Comment by layday** [comment]
Logs please if you have them.  They'll be under the `__jsonrpc__` profile for the GUI.

**Comment by peterweissbier** [comment]
there doesnt seem to be an error log. it only happens now when i first start the program, if i close it and restart any amount of times, it wont happen

**Comment by layday** [comment]
Are you sure there are no logs under `%AppData%\instawow\profiles\__jsonrpc__\logs`?

**Comment by peterweissbier** [comment]
well i renamed the old log to error1.log so i can see if theres a new log and there wasnt

[error1.log](https://github.com/user-attachments/files/15945524/error1.log)

**Comment by layday** [comment]
Fixed in v4.4.2, thank you for reporting.

**Comment by peterweissbier** [comment]
very good
