### ISSUE TITLE
Update addon’s target and priority order

### ISSUE THREAD

**Issue by Char11e** [layday/instawow#148]
1. Is addon updated by comparing the plug-in name and version number in the folder?

2. What is the update priority of the addon source library?
It is currently known that instawow-gui will use addon sources such as cruse, wago, tukui, wowi, github and so on.

**Comment by layday** [comment]
1. By comparing the version from source against the version in instawow’s database.
2. Add-ons will always be updated using the installation source. Changing sources must be done manually.

**Comment by Char11e** [comment]
Thank you for your answer, because I am currently using instawow-gui-4.7.0 and found that the plug-in will only use wowi ID for comparison and will not use other IDs for comparison.

**Comment by layday** [comment]
Do you mean for reconciliation? What other IDs do exist? Note that CurseForge won’t be loaded without an access token and GitHub’s usage limit is easy to exceed without a token.

**Comment by Char11e** [comment]
![image](https://github.com/user-attachments/assets/d2f59bbc-bc32-4c27-9585-a2e210d25beb)

Currently, after I add the github token, for example, "AutoPotion" originally showed updates using wowi sources, but now it changes to github.

But "!!!gmFonts" still shows using wowi source, does it mean because !!!gmFonts and there are github sources from the following csv table.

https://raw.githubusercontent.com/layday/github-wow-addon-catalogue/main/addons.csv

Is the current source update priority the following situation? (As long as there is a token):
github > cruse > wago > wowi

Thank you very much for your patient answer!

**Comment by Char11e** [comment]
Understood, thank you!
