### ISSUE TITLE
403 reconciling against Wowinterface

### ISSUE THREAD

**Issue by twocows** [layday/instawow#151]
New setup of instawow, getting a 403 trying to reconcile against Wowinterface sources. Possibly rate-limited but the output doesn't say so specifically. Example output:
✗ github:deadlybossmods/dbm-cataclysm
  package is not installed
! wowi:21469-deadly-boss-mods-cataclysm-mods
  internal error: "403, message='Forbidden', url='https://cdn.wowinter
    face.com/downloads/getfile.php?id=21469&d=1727497583&minion'"

Loading up that URL in Firefox seems to work just fine and prompts for a download, so the site should be reachable.

**Comment by layday** [comment]
I'm not sure if the HTTP response says so specifically either; it looks like a generic 403.  I've never experienced this with WoWI.  Did you have a large volume of WoWI add-ons?

**Comment by twocows** [comment]
I think it was maybe 10 or so.

**Comment by layday** [comment]
Were you able to rerun reconciliation on these add-ons?

**Comment by twocows** [comment]
I tried to re-reconcile it several times yesterday and the 403s were still happening. I've moved onto another solution so unfortunately I can't offer any more detail, but my addons didn't seem to be broken or anything so I expect it probably cleaned up its state just fine. You can probably close this one out; unless you wanted to look into it more yourself; thank you for trying to help.

**Comment by layday** [comment]
Alright, thank you.

**Comment by layday** [comment]
I'm reopening this since I'm observing it too now. aiohttp appears to be triggering CloudFlare's bullshit.

**Comment by layday** [comment]
The issue seems to be that CloudFlare thinks that supporting both TLS 1.2 and 1.3 at the same time is unacceptable: https://github.com/aio-libs/aiohttp/discussions/9300#discussioncomment-10775829. Just, what.

**Comment by layday** [comment]
Fixed in v4.8.0.
