### ISSUE TITLE
Conflicting addons that should be able to be installed together

### ISSUE THREAD

**Issue by seirl** [layday/instawow#18]
When I run:

```
instawow install https://www.curseforge.com/wow/addons/mechagon-rare-share
instawow install https://www.curseforge.com/wow/addons/nazjatar-rare-share
```

I get:

    package folders conflict with installed package's curse:mechagon-rare-share 

I'm pretty sure these addons are supposed to be compatible together, I've seen multiple people with both of them. Is there a restriction that needs to be relaxed?.

**Comment by layday** [comment]
Both of these add-ons contain a 'RareShare' folder and *instawow* works on the assumption that add-on folders should not conflict.

**Comment by seirl** [comment]
Right, so I suppose this is different from the behavior of the official curse client?

**Comment by layday** [comment]
The official client will let you to install both but when you uninstall either of the two the RareShare folder is deleted and the remaining add-on stops working.

**Comment by seirl** [comment]
Yikes that's bad. I guess that's something that should be reported to the person who wrote the addon then...

I assume that you want to keep the current behavior if you think it's more sensible than what the official client does, so I'll close this for now.

**Comment by layday** [comment]
Looks like the author has heard my pleas.  *instawow* doesn't resolve Curse dependencies so you still have to install the core add-on separately.

**Comment by seirl** [comment]
Should we file an issue for resolving Curse dependencies? :-)

**Comment by layday** [comment]
Perhaps though I feel like it would add a lot of unwelcome complexity and I loathe writing tests ;)

**Comment by layday** [comment]
Added in v1.6.0.

**Comment by seirl** [comment]
Hah, amazing!
