### ISSUE TITLE
[Not an Issue, Seeking Help] How to update instawow

### ISSUE THREAD

**Issue by Pariah** [layday/instawow#22]
I received a message today that instawow was not up to date. I tried to use 'pip3 install instawow' and then pip3 help to find a command that would allow for me to upgrade but I wasn't able to find the command. Is upgrading a possibility or do I need to uninstall and reinstall your application?

I'm sure this is an idiotic question for you and I tried to avoid asking it by Googling but I'm somewhat out of my element here.

Cheers.

**Comment by layday** [comment]
Hey @Pariah, to update packages from pip you need to pass `-U` or (`--upgrade`) to `install`:

    pip3 install -U instawow

**Comment by Pariah** [comment]
@layday Thank you very much for your help. And your work. Cheers.
