### ISSUE TITLE
Can't install instawow in Windows with different default locale

### ISSUE THREAD

**Issue by luhao007** [layday/instawow#24]
Got the below error when install:

`    ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\luhao\\AppData\\Local\\Temp\\pip-req-build-n5e1ezlw\\setup.py'"'"'; __file__='"'"'C:\\Users\\luhao\\AppData\\Local\\Temp\\pip-req-build-n5e1ezlw\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\luhao\AppData\Local\Temp\pip-req-build-n5e1ezlw\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\luhao\AppData\Local\Temp\pip-req-build-n5e1ezlw\setup.py", line 17, in <module>
        long_description=Path('README.rst').read_text(),
      File "c:\python37\lib\pathlib.py", line 1207, in read_text
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 2233: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

It should be able to be fixed by passing in "encoding='utf-8‘" in "read_text()"

**Comment by layday** [comment]
Thanks for the report.
