### ISSUE TITLE
Reconcile won't work without manager.resolvers['curse'].folders_url

### ISSUE THREAD

**Issue by kurumushi** [layday/instawow#26]
In commit 6881d8138e2389f65bde26cee38f35fe2544d42e, you removed folders_url from the CurseResolver class. This is still needed for reconcile to work. Not sure if it's something in progress or a bug.

**Comment by layday** [comment]
Well, that's embarrassing (though reconcile does say it's untested on the tin *cough*).

**Comment by layday** [comment]
Thanks again for the report.
