### ISSUE TITLE
Old version (1.6.0) in pypi repository

### ISSUE THREAD

**Issue by dieterdanger** [layday/instawow#29]
Hello,
I get errors when trying to update addons and I think it might be related to the version of instawow I'm using. The github files are newer than the ones on pypi.org. Could you update these?

Best regards

**Comment by layday** [comment]
What errors are you getting?

**Comment by layday** [comment]
If *instawow* says that it 'encountered an error' you can issue `instawow show-config` to locate your configuration folder.  From there you will find the error log in `logs/error.log`.

**Comment by dieterdanger** [comment]
sorry, my fault. addon folder was wrongly configured.
