### ISSUE TITLE
Add-ons missing from CF POST API

### ISSUE THREAD

**Issue by layday** [layday/instawow#30]
```
$ # DBM is okay
$ http get https://addons-ecs.forgesvc.net/api/v2/addon/3358 -b | jq .id
3358
$ echo [3358] | http post https://addons-ecs.forgesvc.net/api/v2/addon -b | jq .[].id
3358
$ # But what about this one?
$ http get https://addons-ecs.forgesvc.net/api/v2/addon/336400 -b | jq .id
336400
$ echo [336400] | http post https://addons-ecs.forgesvc.net/api/v2/addon -b | jq .
[]
$ # Uh...
```

I'll wait and see if this resolves itself for now.

**Comment by layday** [comment]
@torkus FYI, not sure if you're using the POST API.

**Comment by torkus** [comment]
no I'm not, but I was admiring the bash work there :)

regarding `addons-ecs.forgesvc.net`, [I have this one](https://github.com/ogri-la/wowman/issues/91) and there was [this complaint](https://old.reddit.com/r/wowaddons/comments/e1bbhz/twitch_addon_manager_installing_classic_versions/?st=k3fqoxfj&sh=e0690d4f) about Twitch misbehaving on the same day.

think they changed something?

![93dfcc0917e9e717bb0ca84f](https://user-images.githubusercontent.com/48790775/69623590-16624f80-1093-11ea-892a-027cc68ad2fa.jpg)

**Comment by layday** [comment]
After further investigation it looks as though add-ons with a `defaultFileId` value of `0` are omitted from the `POST` response.  Either the API was changed or the `defaultFileId` was wiped from  `336400` and a bunch of other add-ons and I don't know which one it is.  I've verified that this also affects the Twitch client though I wish I hadn't.

**Comment by torkus** [comment]
> I've verified that this also affects the Twitch client though I wish I hadn't.

# :sob:

> add-ons with a defaultFileId value of 0 are omitted from the POST response

That sounds like a very strange edge case. It's weird to have IDs starting at 0 rather than 1 anyway.

Why are you sending POST requests anyway? I know they have another API used for managing addons that makes use of POST

**Comment by layday** [comment]
You can use POST to make bulk requests so instead of firing off a GET for every add-on you have installed:

```
$ echo [23350, 15226] | http post https://addons-ecs.forgesvc.net/api/v2/addon -b | jq '.[] | [.id, .name]'
[
  15226,
  "Grid2"
]
[
  23350,
  "AdiBags"
]
```

**Comment by torkus** [comment]
ah, very cool. wowman doesn't support that model unfortunately. possibly in the future when I've exhausted all other features to implement ;) or curseforge ban it's useragent for spamming.

**Comment by layday** [comment]
I would imagine the traffic generated by wowman and instawow combined is minuscule compared to their own client's.

**Comment by torkus** [comment]
definitely. I was very pleased with my 1k downloads of wowman, but the much more recent erikabp123/ClassicAddonManager has 7.1k, and that is a windows-only, classic-only addon manager.

**Comment by torkus** [comment]
another possibly related issue: https://github.com/AcidWeb/CurseBreaker/issues/38

**Comment by layday** [comment]
This appears to have affected only a very small [number](https://github.com/layday/instascrape/commit/6f0b155c219043ba205815c92f78d6f0160649e1) of add-ons.  Not much I can do I suppose - it'll get fixed whenever the authors get around to publishing a new version of their add-on 🤷‍♀️

**Comment by AcidWeb** [comment]
This is rare but occurring CF API error not connected with Twitch client issues.
It is fixing itself after few hours and don't require publishing new version of addon.

**Comment by layday** [comment]
[BtWLoadouts](https://www.curseforge.com/wow/addons/btwloadouts) had a 0 `defaultFileId` for a little while though it did have files associated with it.  That went away when the author uploaded a new version, which is why I postulated they'd have to upload a new version but ya, suppose it might've only been BtWLoadouts.
