### ISSUE TITLE
How to use the 'any_flavour' strategy?

### ISSUE THREAD

**Issue by GotekSC** [layday/instawow#34]
When I try to install a retail addon to my classic configuration I get this:
```
┌─[gotek][warsong:~]
└─▪iwowc install https://www.curseforge.com/wow/addons/colorpickerplus            
✗ curse:colorpickerplus
  no files compatible with classic using 'default' strategy
```
From which I can surmise that I should somehow use the 'any_flavour' strategy mentioned in the readme. But how exactly do I do this? I couldn't find any documentation on it.

**Comment by layday** [comment]
Like this:

```
iwowc install -s any_flavour https://www.curseforge.com/wow/addons/colorpickerplus
```

I'll add it as an example though do note the readme is not exhaustive but the help text is: `iwowc install --help` :)

**Comment by GotekSC** [comment]
Thank you. Have a nice day :)
