### ISSUE TITLE
Unable to install RealUI with intstawow

### ISSUE THREAD

**Issue by nicktfried** [layday/instawow#38]
I'm unable to install realUI with instawow, unsure if that is desired or not

URL: https://www.wowinterface.com/downloads/info16068-RealUI.html

P.S. LOVE this product thank you for your work.

**Comment by layday** [comment]
Thank you for the kind words.  Regrettably, UIs are not available from the WoWI API which is why *instawow* cannot find RealUI - it's an omission on WoWI's part.  You could try asking the author if they'd be willing to release RealUI on CurseForge.

**Comment by nicktfried** [comment]
Thanks!

**Comment by layday** [comment]
FYI, the latest version of instawow is able to install and update RealUI from [GitHub](https://github.com/RealUI/RealUI).

**Comment by nicktfried** [comment]
Thank you!

--
Nick
