### ISSUE TITLE
TradeSkillMaster updater

### ISSUE THREAD

**Issue by mspykerez** [layday/instawow#39]
Add support to update TradeSkillMaster data (similar to what this does here: https://github.com/camas/grunt) ?

**Comment by layday** [comment]
It looks like this updates an auxiliary add-on using API data in a similar fashion to WeakAuras Companion, althooough Grunt appears to assume ownership of the main TSM add-on as well, so there might be more than meets the eye.  I've never used TSM, so I'd have to install it as well as their desktop app to get a clearer picture.

**Comment by layday** [comment]
The TSM app uses a closed API which requires authentication - my immediate thought is no, I don't want to be passing around usernames, e-mails, passwords or even session tokens.  TSM has a separate, rate-limited [API](http://api.tradeskillmaster.com/docs/) intended for public use but whether this provides all the necessary data to update the add-on I do not know (I would guess not).

**Comment by layday** [comment]
I'm reading that TSM would disapprove of cloning their desktop app (https://github.com/AcidWeb/CurseBreaker/issues/120); taking everything into consideration, I'm disinclined to work on adding support for TSM.
