### ISSUE TITLE
'package does not exist' when trying to update addons

### ISSUE THREAD

**Issue by boyblunder** [layday/instawow#40]
I'm getting the below errors when trying to update my addons. This is on a MacBook Pro. I suspect something changed on the Curse website?

$ instawow-classic update
✗ curse:decursive
  package does not exist
✗ curse:bagnon
  package does not exist

**Comment by layday** [comment]
instawow is technically correct.  As of writing, both of those add-ons are missing from the CurseForge API.  This is the API response for Decursive, which has an internal ID of 2154:

```
$ curl -I https://addons-ecs.forgesvc.net/api/v2/addon/2154
HTTP/2 404
date: Wed, 12 Aug 2020 13:21:50 GMT
x-cache: Error from cloudfront
via: 1.1 d25f94f2d8cb5a09e7453f0d9bc58eae.cloudfront.net (CloudFront)
x-amz-cf-pop: ATH50-C1
x-amz-cf-id: wVrSkNW2Di97OL7qdTYUIncv6-J__WtAYsYp8lHEYZZsTVxltglkvA==
```

There's nothing I can do on my side; Twitch users are experiencing the same issue.

**Comment by layday** [comment]
Looks like things are working again on the CF end, closing.
