### ISSUE TITLE
Change strategy of installed addon

### ISSUE THREAD

**Issue by hauk92** [layday/instawow#47]
I'm trying to change the strategy of an installed addon from default to curse_latest_beta (is this even possible?).

I tried for example:
```
instawow install -o -s curse_latest_beta curse:grid2
✗ curse:grid2
  package already installed
```

This is possibly a feature or a documentation request.
Btw thanks for the fast fix of the previous issue!

**Comment by layday** [comment]
This is not possible from the CLI.  It's not obvious from the help text but `-o` only works with add-ons which instawow isn't tracking - you can't replace an installed add-on.  If you want to install an add-on using a different strategy, you've got to remove it first:

```
instawow remove curse:grid2
instawow install -s curse_latest_beta curse:grid2
```

(Unless you're specifically targetting beta releases, you might also want to consider `latest`, which will install the latest stable version if it happens to be more recent than the beta.)

**Comment by hauk92** [comment]
Thanks for the clarification and the hint to "latest". As far as I'm concerned this issue can be closed.

**Comment by layday** [comment]
I think strategy switch on update would prove useful if you could *preview* changes in the CLI (e.g. if a `--dry-run` mode were available) but is otherwise not worth the additional complexity.  Will revisit if I implement dry run.
