### ISSUE TITLE
Rollback to nonexistent version deinstalls addon

### ISSUE THREAD

**Issue by hauk92** [layday/instawow#50]
The "r978-classic" version of [grid2](https://www.curseforge.com/wow/addons/grid2/files) was previously tagged as "r978-beta-classic". If I roll back to "r978-beta-classic" this just leads to grid2 being removed.

Output
```
instawow rollback curse:grid2
- Select version of curse:grid2 for rollback  r978-beta-classic
✓ curse:grid2
  removed
✗ curse:grid2
  no files compatible with classic using 'version' strategy
```

**Comment by hauk92** [comment]
Already fixed. I was using an old version, sorry.

**Comment by layday** [comment]
Yes, some authors are in the unfortunate habit of renaming their alpha and beta releases and retagging them as stable. I assume “r978-beta-classic” is now “r978-classic”.
