### ISSUE TITLE
Can't find some addons

### ISSUE THREAD

**Issue by scalp42** [layday/instawow#55]
Hi @layday 

Thanks for instawow 👏 

I noticed that some addons don't show up when searching for them (and can't be reconciled either):

- [Adibags_Garrison](https://www.curseforge.com/wow/addons/adibags_garrison)
- [WhoLusted](https://www.curseforge.com/wow/addons/wholusted)

Any ideas?

**Comment by layday** [comment]
HI @scalp42 - thanks for using instawow!  Old add-ons are not included in the catalogue to reduce noise and keep its size down - you can install these by pasting the URL directly into the search box in the GUI or by passing it as an argument to `install` in the CLI.  The cut-off for the catalogue is the release date of the Legion pre-patch in Aug 2017.  Perhaps I could provide the complete catalogue as an option if there's interest.

**Comment by scalp42** [comment]
The URL pasting trick will do!

Thanks 🙏

**Comment by scalp42** [comment]
@layday it doesn't seem to work

![Screen Shot 2020-10-14 at 18 35 30](https://user-images.githubusercontent.com/1475276/96063140-21a99f80-0e4c-11eb-8bd7-093a0f2ad397.png)

Try pasting `https://www.curseforge.com/wow/addons/wholusted` and other combinations but no luck.

**Comment by layday** [comment]
Ah yes, for CurseForge the URL is paired with the ID from the catalogue.  As a temporary workaround you can use the add-on ID from the column on the right:

<img width="912" alt="Screenshot 2020-10-15 at 04 39 32" src="https://user-images.githubusercontent.com/31134424/96063730-7a0a8c80-0ea0-11eb-98c5-589356944dc1.png">

**Comment by scalp42** [comment]
Argh that'll do it!

Thanks again for the speedy answers, much appreciated.

**Comment by suroh1994** [comment]
I just setup instawow and I encountered the same problem with one of my addons.
[Adibags BoE & BoA](https://www.curseforge.com/wow/addons/adibags-boe-boa)

I did try to paste the URL in the CLI but that didn't work for me. Am I doing something wrong?

```
instawow install https://www.curseforge.com/wow/addons/adibags-boe-boa
✗ curse:adibags-boe-boa
  package does not exist
```

**Comment by layday** [comment]
```
instawow install curse:89177
```

**Comment by suroh1994** [comment]
Ah! Ok, now I understand. 
I was confused where to find the ID you were speaking of. Now I understand it. It's the project ID on the curseforge page. My bad! I'll give it a go, when I got some time later tonight. Thanks for the fast response.

**Comment by scalp42** [comment]
@layday dont want to reopen the issue but do you have an idea how to install https://www.curseforge.com/wow/addons/pretty-reps?

![image](https://user-images.githubusercontent.com/1475276/110067880-6a91c000-7d29-11eb-85b4-acd5bcd3d023.png)

**Comment by layday** [comment]
Projects which were marked as abandoned during the migration to Overwolf are excluded from CF API batch responses.  There's currently no way around this.

**Comment by scalp42** [comment]
@layday thanks for the quick response!
