### ISSUE TITLE
Unable to buid the WA-companion

### ISSUE THREAD

**Issue by nicktfried** [layday/instawow#57]
Hi love the product, I'm unable to build the WA companion on my mac through PipX getting the following error:

in read
    await self._waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

May be because of the prepatch surge but wanted to check to be sure.

**Comment by layday** [comment]
Yeah, the Wago API is down or very slow to respond - nothing I can do on my end :(

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nicktfried** [comment]
All good I’ll close it out!
