### ISSUE TITLE
macOS first startup problem

### ISSUE THREAD

**Issue by jcrate** [layday/instawow#6]
environment: macOS 10.13.6, python 3.7 installed with homebrew

When starting up for the first time, instawow gives an error that the addon directory cannot be found. The default addon directory it is looking for does exist. However, the config directory was not created. Running the following code from instawow in a python interpreter creates the config directory:

```
from os import environ
from pathlib import Path
import click

configdir = Path(click.get_app_dir('instawow'))
configdir.mkdir(exist_ok=True)

```

The directory was created with or without the exist_ok parameter. After creating the config directory this way, instawow launches fine. If I remove the config directory, instawow doesn't create it, even though the code instawow uses to create the directory works in the interpreter.  

I'm not familiar with python, but it looks like it might be possible it's trying to validate that the configuration directory exists **before** trying to create it.

**Comment by layday** [comment]
This sounds like a regression.  I'll take a look in a bit.

**Comment by layday** [comment]
Fixed in the latest version.  Thanks for the detailed report!
