### ISSUE TITLE
AttributeError regarding missing attribute in GlobalConfig in 1.17.1

### ISSUE THREAD

**Issue by BSerpent86** [layday/instawow#61]
When running my installed and previously working instawow 1.17.1, I get the following error:
`AttributeError: 'GlobalConfig' object has no attribute '__field_defaults__'`

When trying to recompile 1.17.1, the build fails due to the same error:
```
tests/test_config.py ..F..F........s...F...s.F

[...]


tests/test_config.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
build/lib/instawow/config.py:99: in read
    dummy_config.migrate_legacy_dirs()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = GlobalConfig(config_dir=PosixPath('/tmp/pytest-of-bs86/pytest-0/test_legacy_profile_migration_1/config'), profile='__d...ovalidate__'), game_flavour='retail', auto_update_check=True, temp_dir=PosixPath('/tmp/pytest-of-bs86/pytest-0/temp0'))

    def migrate_legacy_dirs(self) -> GlobalConfig:
        "Migrate a profile-less configuration to the new format."
        legacy_config_file = self.config_dir / 'config.json'
        if (
>           self.profile == self.__field_defaults__['profile']
            and not self.profile_dir.exists()
            and legacy_config_file.exists()
        ):
E       AttributeError: 'GlobalConfig' object has no attribute '__field_defaults__'
```

**Comment by layday** [comment]
Thanks for the bug report. It would help to know how you installed instawow. It looks like you have Pydantic 1.7 but the declared dependency is 1.6.*.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BSerpent86** [comment]
I have it installed on Manjaro using the AUR:
https://aur.archlinux.org/packages/instawow/
The install script can be found here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=instawow

It checks for 'python-pydantic>=1.6.1'

Yes, python-pydantic is at version 1.7.2 on Arch based distributions, there is no 1.6 available anymore. Python is at 3.8.6

**Comment by layday** [comment]
@kelaun, could you take a look hero please?

**Comment by kelaun** [comment]
Hi @BSerpent86,

This was overlooked on my end in the PKGBUILD.
I will roll out a fix for it.
What you can do is install downgrade with `yay -S downgrade` and run `sudo downgrade python-pydantic`. There you can downgrade to version 1.6.1 and after that it will work again.

**Comment by BSerpent86** [comment]
Thanks, did that workaround and it is working again. 
I don't think that keeping a package on an old revision can be a permanent solution though.

**Comment by kelaun** [comment]
It is not a solution indeed.
Looking at the source however, the next release will be compatible with 1.7.x according to the setup.py

**Comment by layday** [comment]
I’m trying to make a new release but unfortunately I’m having some internet issues.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by layday** [comment]
I've published 1.18.0 which depends on Pydantic 1.7.*.

@kelaun, you can also drop the dependency on `python-slpp-git`.

**Comment by kelaun** [comment]
The package was updated on the AUR as well now and seems to work fine.

**Comment by BSerpent86** [comment]
Thanks, its working again now without downgrading anything!

**Comment by layday** [comment]
Thanks for the report @BSerpent86 and thanks for your help @kelaun!
