### ISSUE TITLE
python-aiohttp dependency can't be fulfilled on Arch

### ISSUE THREAD

**Issue by BSerpent86** [layday/instawow#63]
Arch updated python-aiohttp to 3.7.3 and python to 3.9.
That now leads to instawow not being usable on Arch, because instawow requires python-aiohttp < 3.7.0

could instawow be updated to use python-aiohttp 3.7?

**Comment by layday** [comment]
*instawow* does not require aiohttp < 3.7.0; it excludes 3.7.0 specifically; Arch has 3.7.3.

@kelaun :)

**Comment by kelaun** [comment]
Hey @layday and @BSerpent86,

This one is on me indeed. I misread the dependency as it needs to be within 3.6 line however it needs to be within the 3.X line.
A fix has been pushed already.

**Comment by BSerpent86** [comment]
Thanks, updated and now all is good and working again!
