### ISSUE TITLE
[1.19.1] https://addons-ecs.forgesvc.net/api/v2/addon HTTP ERROR 404

### ISSUE THREAD

**Issue by EnochTheWise** [layday/instawow#64]
Hi, i'm update instawow and now:
```
$ instawow update
! curse:acp
  internal error: "Connection timeout to host https://addons-
    ecs.forgesvc.net/api/v2/addon"
! curse:capping-bg-timers
  internal error: "Connection timeout to host https://addons-
    ecs.forgesvc.net/api/v2/addon"
! curse:deadly-boss-mods
  internal error: "Connection timeout to host https://addons-
    ecs.forgesvc.net/api/v2/addon"
```

:`(

**Comment by layday** [comment]
That's not a 404; it's a timeout, because of a network issue either on your side on CurseForge's.

**Comment by EnochTheWise** [comment]
hmmm

```
$ dig addons-ecs.forgesvc.net @8.8.8.8

; <<>> DiG 9.16.1-Ubuntu <<>> addons-ecs.forgesvc.net @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27128
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;addons-ecs.forgesvc.net.       IN      A

;; ANSWER SECTION:
addons-ecs.forgesvc.net. 59     IN      A       52.85.114.61
addons-ecs.forgesvc.net. 59     IN      A       52.85.114.89
addons-ecs.forgesvc.net. 59     IN      A       52.85.114.37
addons-ecs.forgesvc.net. 59     IN      A       52.85.114.103

;; Query time: 88 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Ср дек 02 19:48:09 +07 2020
;; MSG SIZE  rcvd: 116
```

From home:
```
$ telnet addons-ecs.forgesvc.net 443
Trying 52.85.238.108...
^C

$ telnet addons-ecs.forgesvc.net 80
Trying 52.85.238.19...
Connected to addons-ecs.forgesvc.net.
Escape character is '^]'.
^]
telnet> quit
Connection closed.```

From router in Nederland:
```
> sys telnet addons-ecs.forgesvc.net port=443    
Connecting to 65.9.68.32
Connected to 65.9.68.32
^C
telnet: read() failed:  Connection reset by peer

Welcome back!

> sys telnet addons-ecs.forgesvc.net port=80 
Connecting to 65.9.68.32
Connected to 65.9.68.32
HTTP/1.1 400 Bad Request
Server: CloudFront
Date: Wed, 02 Dec 2020 12:56:04 GMT
Content-Type: text/html
Content-Length: 915
Connection: close
X-Cache: Error from cloudfront
Via: 1.1 c888f786e25e6e3c7dbb7e9da462d715.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: FRA56-C1
X-Amz-Cf-Id: rUTNf5kL3Gh53JjJZtiFLtbRVcIOftQGjTEycnZb6Z877iiMKvd5xQ==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>400 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: rUTNf5kL3Gh53JjJZtiFLtbRVcIOftQGjTEycnZb6Z877iiMKvd5xQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>Remote closed connection: 65.9.68.32

Welcome back!
```
seems like a server problem... :`(

**Comment by layday** [comment]
Yeah, it looks like it might be a CloudFront outage in your region.

**Comment by EnochTheWise** [comment]
> it looks like it might be a CloudFront outage in your region.
Yep...
Everything works today!
Thank you! 8)
