### ISSUE TITLE
[Feature] Improve search by listing information

### ISSUE THREAD

**Issue by Industrial** [layday/instawow#65]
Hi!

I love this tool. Thanks for creating it. Finally, a simple way to install and update AddOns that doesn't hog RAM, is fast and even leaves my own addon's dir (which is in development) alone (unlike Minion).

What I'm missing is a package manager like functionality that can list search results based on a search query, matching results in the title, description or other fields. I guess having a local db of addons (at least, i saw a sqlite file in `~/.config/instawow/`) could make the implementation a simple `SELECT` query :D.

What do you think?

gr,

Tom

**Comment by layday** [comment]
Hi and thanks for the kind words!  A few questions:

* Do you mean that you want to query installed add-ons or the catalogue of installable add-ons?
* Do you want more information to be shown when listing search results, or do you only want to be able to search in fields other than the title?
* Is this for the CLI or the GUI?

**Comment by layday** [comment]
I'll close this now but feel free to respond when convenient.
