### ISSUE TITLE
Support installation through Github.

### ISSUE THREAD

**Issue by Zerophase** [layday/instawow#69]
I've noticed a few packages having multiple updates on their github releases, but nothing for a couple weeks in the repository. Is there any possibility of adding a check that reconciles with versions on github as well?

**Comment by layday** [comment]
instawow supports GH releases.  If you'd like to switch from e.g. CF to GH, you have to uninstall the CF add-on and reinstall from GH.

**Comment by layday** [comment]
If you're asking whether instawow could check for updates from multiple sources, that would require manual intervention for add-ons without source IDs in their TOC.  I'm not aware of any add-on which includes a TOC entry for GitHub.
