### ISSUE TITLE
townlong-yak support doesn't seem to be there

### ISSUE THREAD

**Issue by Rubio9** [layday/instawow#70]
The readme says there is support for managing packages from townlong-yak.
How is this done?

$ instawow install https://www.townlong-yak.com/addons/venture-plan
✗ https://www.townlong-yak.com/addons/venture-plan
  package source is invalid
$ instawow install https://www.townlong-yak.com/addons/venture-plan/
✗ https://www.townlong-yak.com/addons/venture-plan/
  package source is invalid
$ instawow install https://www.townlong-yak.com/addons/venture-plan/release
✗ https://www.townlong-yak.com/addons/venture-plan/release
  package source is invalid
$ instawow install https://www.townlong-yak.com/addons/venture-plan/release/
✗ https://www.townlong-yak.com/addons/venture-plan/release/
  package source is invalid
$ instawow install https://www.townlong-yak.com/addons/ul/d0dab99a55d9582427c5707ff9489dd76b33d904/VenturePlan-4.13.zip
✗ https://www.townlong-yak.com/addons/ul/d0dab99a55d9582427c5707ff9489dd76b33d904/VenturePlan-4.13.zip
  package source is invalid

Also, instawow search knows nothing about Venture Plan -- and only knows about Master Plan and War Plan, the other two addons at townlong-yak, because they're also on Curse.

**Comment by layday** [comment]
I'm sorry about the confusion - there's not been a release with TY support yet.  In the meantime, you're welcome to use the [plug-in](https://github.com/layday/instawow-townlong-yak-plugin) if you've installed *instawow* with pip(x).

**Comment by layday** [comment]
v1.21.0 is out with support for Townlong Yak.

**Comment by Rubio9** [comment]
Thanks, that was quick - but still having an issue.

$ instawow install townlong-yak:venture-plan
Downloading install.zip     0% [                                                      #          ] 0.0/  ? eta [?:??:??]
   <does this for a while with the # zipping across the screen but no actual progress, and then>
! townlong-yak:venture-plan
  internal error: "Response payload is not completed"

**Comment by layday** [comment]
That looks like a network issue. Can you try again?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Rubio9** [comment]
Actually, it appears to have been due to an old copy of aiohttp (aiohttp-3.6.2).
Removed that and let it install a new aiohttp (aiohttp-3.7.4.post0) and it worked correctly.
Probably some stricter dependency for aiohttp is needed.

**Comment by layday** [comment]
Ah, thanks, that's very helpful.

**Comment by layday** [comment]
Fixed in v1.21.0.post1.
