### ISSUE TITLE
Updated addon to wrong game version (BC Classic 2.5.1 instead of Retail 9.0.5)

### ISSUE THREAD

**Issue by suroh1994** [layday/instawow#75]
I just ran into an issue with instawow and plater. The latest update of plater-nameplates on curseforge is for the BC beta. But apparently my installation of instawow did not realize that and installed it into my retail addons directory and now I'm being bombarded with error messages. 

Is this a setup error on my end or is instawow not checking the game version?

**Comment by layday** [comment]
Do you have the latest version of instawow (v1.23.0)?

**Comment by suroh1994** [comment]
I did not, I still had 1.20.0.post1

Updated to 1.23.0 and now it updated to the correct version 👍

**Comment by layday** [comment]
Yeah, I didn't anticipate that the addition of TBC on CF would interfere with retail updates, sorry about that.
