### ISSUE TITLE
Register Cert with desktop app with Apple and adding it to homebrew for easy install 

### ISSUE THREAD

**Issue by nicktfried** [layday/instawow#77]
Hi I was wondering if you had considered register the macos app with Apple to avoid having to circumvent security settings and also adding the binaries to homebrew for a slightly easier install.

Love the app! Thanks for all the hard work!

**Comment by layday** [comment]
Well, this being something of a hobby project, I'm not sure if I can justify blowing $100 per annum on an Apple developer sub to be able to sign and notarise apps on macOS.  I'll give it some more thought.

As for Homebrew, I don't personally use it, but anyone's free to publish a formula for the CLI or a cask for the GUI (assuming *instawow* meets their criteria for inclusion).

Appreciate the kind words.

**Comment by nicktfried** [comment]
Yikes! Didn’t know you needed to pay just to get the cert 

Also I think I can publish the formula for home brew. I’ll give it a shot! Thanks the response
