### ISSUE TITLE
Instawow not workiung properly for TBC

### ISSUE THREAD

**Issue by ychmi** [layday/instawow#78]
Hi, 
always been a big fan of this tool (IMO the only real autoupdater!) but now I am really struggling to install (correct) addons for tbc classic.  

**Example 1:** When trying to install ElvUI tbc using the link https://www.tukui.org/classic-tbc-addons.php?id=2 I get hit with 
 ```
✗ https://www.tukui.org/classic-tbc-addons.php?id=2
 package source is invalid 
```   

**Example 2:** There is no way for me to select the correct WeakAuras version (I am greeted with the warning about the version being incorrect ingame):
```
instawow -p classic search weakauras
Select add-ons to install  (use arrow keys to move, <space> to select, <o> to view in your browser)
 » WeakAuras Companion  (instawow:weakauras-companion-autoupdate==f30233a)
   WeakAuras  (curse:weakauras-2==3.4.2-classic)
   WeakAuras 2  (wowi:24910-weakauras-2==3.4.2)
   DejaAuras  (curse:dejaauras==1307r002)
   TweakMainMenuBar  (wowi:25871-tweakmainmenubar==1)
   idTweaks  (wowi:23978-idtweaks==v3.2.0)
   idTweaks  (curse:idtweaks==v1.13.2-1.20.1-classic)
   AutoAura  (curse:autoaura==AutoAura-v1.24.zip)
   DejaAuras (Universal)  (wowi:24651-dejaauras-universal==905r002)
   DarkNameplates  (curse:darknameplates==DarkNameplates)
   Audio Tweaks - Warrior  (wowi:24262-audio-tweaks-warrior==1)
```
(none of the above are correct for tbc classic, which would be 2.5.1)  

What I already tried:
- Latest version (```instawow --version``` returns ```instawow, version 1.24.0```)
- Did reinstall instawow AND
- Cleaned folders in ```C:\Users\<User>\AppData\Roaming\instawow\profiles\```, then ran ```instawow configure``` and ```instawow -p classic configure```
- ```instawow -p classic configure``` correctly suggested the "Classic" flavor

What am I doing wrong or missing?

**Comment by layday** [comment]
Apologies, I haven't been able to cut a release with TBC support yet. I will do so later tonight or tomorrow.

**Comment by layday** [comment]
(If you'd like, you can download the latest development version from https://github.com/layday/instawow/actions/runs/913143520.)

**Comment by ychmi** [comment]
No pressure! I was just skimming the source code and from that it looked TBC ready. I did not connect the dots that the latest release is older than the commits with the TBC changes. Thank you!

**Comment by layday** [comment]
I released a new version yesterday.  Please let me know if you face any problems.
