### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by toastmonger** [layday/instawow#8]
New (to me) error that's been occurring for the last couple of days:

> instawow update
Checking:  16%|######3                                | 13/80 [00:01<00:14,  4.73it/s]Fatal error on transport
protocol: <uvloop.loop.SSLProtocol object at 0x108dd5a58>
transport: <TCPTransport closed=False reading=False 0x7fe9ca663ca8>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 573, in uvloop.loop.SSLProtocol._do_shutdown
  File "/Users/jeremy/miniconda3/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Checking:  49%|###################                    | 39/80 [00:03<00:02, 16.39it/s]Fatal error on transport
protocol: <uvloop.loop.SSLProtocol object at 0x108dd51b8>
transport: <TCPTransport closed=False reading=False 0x7fe9cd748df8>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 573, in uvloop.loop.SSLProtocol._do_shutdown
  File "/Users/XXXXXXX/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
✗ curse:quartz                                                                        
  package does not exist
✗ curse:bazooka
  package does not exist
Thu Jun 06 20:51:54> 

If it helps:

 > instawow --version
instawow, version 1.0.0

**Comment by layday** [comment]
This appears to be an issue with Python 3.7.3 and will be fixed .4 (https://github.com/aio-libs/aiohttp/issues/3535).  I'll see if there's anything I can do to mitigate it in the meantime.

**Comment by toastmonger** [comment]
Thanks for checking into this!

**Comment by toastmonger** [comment]
Whatever you've done in the last update seems to have helped, thank you!

**Comment by layday** [comment]
Good to hear! I'll go ahead and close this issue then.
