### ISSUE TITLE
curse:addon-name - package does not exist

### ISSUE THREAD

**Issue by dieterdanger** [layday/instawow#9]
Hello,
since today the plugin shows me for example

curse:weakauras-2
package does not exist

for every curse plugin. Do you have a clue or the same problem?

Best regards

**Comment by Booleanperspective** [comment]
Same issue here, on Arch Linux with Python 3.7.3.

**Comment by painintheass** [comment]
The issue is that curseforge changed their website. This will require the developer's attention.

**Comment by dieterdanger** [comment]
Thanks for the quick help! Could you update the pip-repository? It's missing dependencies for me and I cannot get it to work right now.

**Comment by Booleanperspective** [comment]
I'm getting dependency issues as well on the pip repo.
