### ISSUE TITLE
Memory leak in Windows 11?

### ISSUE THREAD

**Issue by DempseyRoller** [layday/instawow#97]
Hey was wondering what was taking up ALL of my 32Gbs of memory and not even showing it in the taskmanager. Apparently the Instawow-GUI was saving it for later use. I'm of course not sure if this is the apps fault or if I've installed it wrong somehow, but it definitely seems this was the cause. When I forced it down my ram usage dropped from 99% to 15%.

**Comment by layday** [comment]
Well, that is worrying. What version of instawow are you using?

**Comment by DempseyRoller** [comment]
It's the latest one. 1.38.1 WhenII looked at the task managers resource monitor it said it has reserved 28Gb of memory. Mind that it doesn't happen instantly. I think I had it on for a day or so. But it has definitely been hogging memory without me noticing at first. I thought it was my WSL at first. Wondered how in earth my Wow could crash because of memory cap.

**Comment by layday** [comment]
There was a memory leak in pythonnet, the GUI library that we're using, that ought to have been fixed in a recent version of instawow.  I'll see if I can debug the Windows client over the weekend.

Thanks for reporting.

**Comment by layday** [comment]
Many weekends have gone by, but the memory leak should be fixed in the latest version.

**Comment by layday** [comment]
I'll close this, let me know if the problem persists (do hope not).
