### ISSUE TITLE
instawow-standalone suddenly getting reported as virus by Avast Free AV

### ISSUE THREAD

**Issue by ZutgKcjA** [layday/instawow#99]
The instawow-standalone.exe is as of today getting reported by Avast Free Antivirus as malware (FileRepMalware [Trj]). What in the world could be causing this?

**Comment by layday** [comment]
No idea, sorry. You could try reporting it as a false positive here: https://www.avast.com/en-us/false-positive-file-form.php.

**Comment by layday** [comment]
There's a new version out so I'll close this - hopefully it won't suffer the same fate.
